baseURL = "https://mms29.github.io/"
languageCode = "en-us"
title = "Remi Vuillemot"
theme = "PaperMod"

[Author]
  name = "Remi Vuillemot"
  # Optional
  homepage = "https://mms29.github.io"
  email = "rvuillemot@gmail.com"